### ISSUE TITLE
Missing DLL on particular device

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/ping-viewer#1018]
## Summary
Version: 2.3.0

Operating System: Windows 10 (Dell tablet-PC)

What is happening: PingViewer errors out on opening with `VCRUNTIME140.dll or VCRUNTIME140_1.dll could not be found` . Only occurs on Dell tablet-PC (not occurring on same person's Desktop computer)

How to reproduce it: Open PingViewer (on relevant device)

## Additional information
- Seems to occur too early for GUI Log to appear
- `VCRUNTIME140.dll` is actually in the directory where the `.exe` is
- more details in [this forum thread](https://discuss.bluerobotics.com/t/pingviewer-problems-starting-and-window-position/10831)

**Comment by ES-Alexander** [comment]
Two others had the same issue [here](https://discuss.bluerobotics.com/t/error-downloading-ping-viewer-to-new-computer/11148), and it was apparently worked around "by downloading and installing Microsoft Visual C++ 2015 - 2019 Redistributable".

**Comment by joaoantoniocardoso** [comment]
Just for safety I did a virus check on our .zip with virustotal and there is [nothing wrong with it](https://www.virustotal.com/gui/file/ba61d4b110dedc62c8c5004bee8a3f78ff9f733b458f0257c88601a2d3f2b672?nocache=1). Also there is [nothing wrong with the shipped dll](https://www.virustotal.com/gui/file/c865c3366a98431ec3a5959cb5ac3966081a43b82dfcd8bfefafe0146b1508db).

Although I assume our [software is being compiled with the same dll version it is shipping](https://doc.qt.io/qt-5/windows-deployment.html#:~:text=same%20compiler%20version%20against%20the%20same%20C%20runtime%20version), if installing (or updating?) vc_runtime has fixed the problem, I was asking myself if it could be something about dll version mismatch..

One possible scenario I can imagine is that for [some reason](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-desktop-applications) the shipped dll is not being found, and the system dll is older than the required, so by updating the system dll the problem is 'fixed'.

To give some data, the version of the latest vc_runtime (which I believe is what they downloaded - [from microsoft](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022)) is `14.30.30704.0`, the classical "2015 Update 3 RC" (which is commonly linked as the solution for the "VCRUNTIME140.dll not found" -  [also from microsoft](https://www.microsoft.com/en-us/download/details.aspx?id=52685)) is `14.0.24123.0`, and the one we ship in our zip is `14.29.30038.0`.

One solution is to recommend the users to update their Visual C++ distribution from the [microsoft link](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist) in advance, just before they run into the problem?

**Comment by patrickelectric** [comment]
Thanks @joaoantoniocardoso, that's an interesting fact!
A possible investigation could be done with [dependency walker](https://www.dependencywalker.com/) to check if the DLL can be found and all dependencies for it exist on the same folder. The weird thing is that we never had this problem until this year, IIRC. 
**VCRUNTIME** exists on the extracted folder and in the same path as **pingviewer.exe**, so it should be found without much problem.

**Comment by Williangalvani** [comment]
I wonder if this is why most software for windows make you install "Visual C++ redistributables" when you install them...

**Comment by joaoantoniocardoso** [comment]
> Thanks @joaoantoniocardoso, that's an interesting fact! A possible investigation could be done with [dependency walker](https://www.dependencywalker.com/) to check if the DLL can be found and all dependencies for it exist on the same folder. The weird thing is that we never had this problem until this year, IIRC. **VCRUNTIME** exists on the extracted folder and in the same path as **pingviewer.exe**, so it should be found without much problem.

Good idea, I'll do that, and I'll also execute our software with the older C++ installed to validate the supposed scenario.

> I wonder if this is why most software for windows make you install "Visual C++ redistributables" when you install them...

hah, I bet so, and actually it seems that when an installer requires administrator privileges, it is using [this (recommended) approach](https://docs.microsoft.com/en-us/cpp/windows/determining-which-dlls-to-redistribute?view=msvc-170#:~:text=Another%20way%20to%20include%20the%20redistributable%20DLLs%20with%20your%20installer%20is%20to%20use%20merge%20modules.%20These%20Microsoft%20Installer%20modules%20are%20included%20in%20and%20installed%20by%20your%20application%20installer.%20Merge%20modules%20for%20the%20redistributable%20DLLs%20are%20found%20in%20your%20Visual%20Studio%20installation%20directory%20under).

Another thing that I noticed that is not exactly following Microsoft's recommendation is that we are copying the DLLs from the system's folder instead copying them from [Visual Studio's redist folder](https://docs.microsoft.com/en-us/cpp/windows/determining-which-dlls-to-redistribute?view=msvc-170#:~:text=directory%20in%20the-,%5CVC%5CRedist%5CMSVC%5Cversion,-folder.%20The%20version), although I noticed that other softwares like Qt Creator [is doing the same](https://github.com/qt-creator/qt-creator/blob/master/.github/workflows/build_cmake.yml#L216). Can we assume they are the same for the [github image](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#microsoft-visual-c)?

**Comment by joaoantoniocardoso** [comment]
Ok, as it is not something I have done in the past, I am detailing the way I came up with the solution:

## Investigation

### Fresh system install

First, by first opening the ping viewer software from a fresh Windows 10 (Stable 1809) virtual machine, the following errors occur:  
![image](https://i.imgur.com/08uINJt.png)
![image](https://i.imgur.com/XmVllnm.png)

That's because we should be packing the `VCRUNTIME_1.dll` and `MSVCP140_1.dll` and we are not.

I renamed the `VCRUNTIME140.DLL` to `tmp` and it says it cannot find `VCRUNTIME140.dll`. That's because the fresh system doesn't have any version installed on the system, and it shows that in absence of system's known DLL on system's dir, the software is, as expected, searching the DLL from the same folder as the `pingviewer.exe`.

### Quick check with Visual C++ Redistributable for Visual Studio 2015

So I installed the [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145)  x64 and installed it to the system:  
![image](https://i.imgur.com/t0ArJ2T.png)

When running pingviewer, again it can't find `VCRUNTIME140_1.dll` and `MSVCP140_1.dll`, and indeed the Redistributable for [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) don't ship these two.

Using Dependency Walker, it shows that the application is using `VCRUNTIME140.dll` that we are shipping, and not from the system32 folder.

### The community's 'fix'

To simulate the steps the user did to fix it, I downloaded and installed the [Latest Microsoft Visual C++ Redistributable](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#:~:text=https%3A//aka.ms/vs/17/release/vc_redist.x64.exe):

![image](https://i.imgur.com/wkhaOUo.png)

And as expected, the software ran smoothly, loading the missing `VCRUNTIME140_1.dll` from the system, which was installed by the Latest Microsoft Visual C++ Redistributable, while using the `VCRUNTIME140.dll` and `MSVCP140.dll` that we ship:

![image](https://i.imgur.com/7K8DIGD.png)

---

## The solution

The solution to our side seems to ship all required DLLs, including (`VCRUNTIME140_1.dll` and `MSVCP140_1.dll`), and to not ship the `ucrtbased.dll`, as it is a Windows's _known_ DLL, which will make it to be searched on the system's folder before our application's folder, and because it is shipped with the Windows itself, we are not supposed to distribute it.

To simulate that, I moved the required DLLs (`VCRUNTIME140.dll`, `VCRUNTIME140_1.dll`, `MSVCP140.dll` and `MSVCP140_1.dll`) from our system's folder (which are the Latest Microsoft Visual C++ Redistributable) to our pingview folder and deleted the `ucrtbased.dll`. The software ran as expected and the Dependency Walker confirms that our software is loading them correctly:  
![image](https://i.imgur.com/XDuq1UA.png)

For reference, Qt Creator is copying [some other dlls](https://github.com/qt-creator/qt-creator/blob/master/.github/workflows/build_cmake.yml#L214) in addition to the four commented here (`VCRUNTIME140.dll`, `VCRUNTIME140_1.dll`, `MSVCP140.dll`, `MSVCP140_1.dll`), but from my tests, just these four are enough for us.

As recommended by @patrickelectric ([and also Microsoft](https://docs.microsoft.com/en-us/cpp/windows/determining-which-dlls-to-redistribute?view=msvc-170#:~:text=One%20way%20to%20collect%20the%20list%20of%20dynamically%20loaded%20DLLs%20is%20to%20run%20Dependency%20Walker)), below I am listing the required DLLs from all the available redistributable DLLs (from [\VC\Redist\MSVC\version](https://docs.microsoft.com/en-us/cpp/windows/determining-which-dlls-to-redistribute?view=msvc-170#:~:text=directory%20in%20the-,%5CVC%5CRedist%5CMSVC%5Cversion,-folder.%20The%20version) - in my case: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Redist\MSVC\14.28.29910\x64\Microsoft.VC142.CRT`):

| Loaded? | DLL                         |
|--------:|:----------------------------|
| N       | concrt140.dll               |
| Y       | msvcp140.dll                |
| Y       | msvcp140_1.dll              |
| N       | msvcp140_2.dll              |
| N       | msvcp140_atomic_wait.dll    |
| N       | msvcp140_codecvt_ids.dll    |
| N       | vccorlib140.dll             |
| Y       | vcruntime140.dll            |
| Y       | vcruntime140_1.dll          |

So, summarizing the solution in simple steps:
- Remove the `ucrtbased.dll`;
- Add the `VCRUNTIME140_1.dll` and `MSVCP140_1.dll`.

### Patch

The patch to our [build.yml](https://github.com/bluerobotics/ping-viewer/blob/master/.github/workflows/build.yml#L53) should be something like:
```diff
+++        SYSTEM32_DLLS: 'VCRUNTIME140.dll VCRUNTIME140_1.dll MSVCP140.dll MSVCP140_1.dll'
---        SYSTEM32_DLLS: 'VCRUNTIME140.dll MSVCP140.dll ucrtbased.dll'
```

---

What do you think?
