### ISSUE TITLE
Ping360 visualizer works at 7Hz

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/ping-viewer#650]
This bug appears to affect only windows.
In general, it appears that everything runs slower on windows, more investigation is necessary.

**Comment by jaxxzer** [comment]
There are at least two problems here:
1. The 2.5M and some other baudrates are not working on Windows. When 2.5M is selected, the communication actually happens at 115200, even when the ping-viewer indications are that it is going at 2.5M. (2M does work correctly on windows).
2. The viewer-side latency and jitter are both huge on windows (need to do more tests to find root cause of latency):
![Screenshot_20190806_134325](https://user-images.githubusercontent.com/8315108/62563254-a2383d80-b850-11e9-9ed5-aa5c15445b70.png)

**Comment by jaxxzer** [comment]
1. is a quick and easy fix @patrickelectric, we should remove the 2.5M baudrate option (the product document will specify 2M maximum).

**Comment by patrickelectric** [comment]
2.5M is the problem ? It works in higher frequencies with 2M ?

**Comment by jaxxzer** [comment]
@patrick, please remove the 2.5M option:
1. It is not allowed according to the product technical specification.
1. It does not work on windows.

**Comment by jaxxzer** [comment]
> 2\. The viewer-side latency and jitter are both huge on windows (need to do more tests to find root cause of latency):

I have some fixes lined up for 2.
