### ISSUE TITLE
ping360: reduce timeout for profile request

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#747]
If we have not received a `ping360_data` message in the last 30 seconds, the timeout should be set to 4 seconds.

When we receive a `ping360_data` message, we can assume the motor is already in position and reduce the timeout to 100ms or so.

We have a problem today, where the ping360 will stop scanning for ~10 seconds when there is a hiccup in communication:
![Screenshot_20190913_133906](https://user-images.githubusercontent.com/8315108/64883345-27232d80-d62d-11e9-8f05-3e1c38c34a4d.png)

**Comment by patrickelectric** [comment]
Not respecting the WCS of 4s that is in the datasheet can result in problems in communication channels that are not full duplex, If I'm not mistaken we have already discussed that and that's why we have a 4.2s timeout, 200ms for the network delay and 4s for sensor WCS.

**Comment by Williangalvani** [comment]
I understand that @jaxxzer 's solution is taking that into account.
The sensor only re-homes if it was idle for 30s. If we just got data from it, we know it is not going to re-home an can use a smaller timeout instead.

We need to be careful and take into consideration the range, baudrate, and possibly the current head position.

But the current behavior of stopping for ~10 seconds because of a dropped packet is not acceptable.
